version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - 210
    environment:
      - APP_NAME=fallback
  fallback:
    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - 80
    environment:
      - APP_NAME=fallback
  lbmain:
    image: dockercloud/haproxy
    links:
      - main
    ports:
      - 8080:210
  lbfallback:
    image: dockercloud/haproxy
    links:
      - fallback
    ports:
      - 80:80