version: '3.8'

services:
  main:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - APP_NAME=main
    ports:
      - 210
  fallback:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - APP_NAME=fallback
    ports:
      - 80
  haproxy:
    image: dockercloud/haproxy
    restart: always
    links:
      - main
      - fallback
    ports:
      - 80:80
      - 210:210
    environment:
      - BALANCE=roundrobin
#      - DOCKER_TLS_VERIFY
#      - DOCKER_HOST
#      - DOCKER_CERT_PATH
#    volumes:
#      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH

networks:
  default:
    internal: true