version: '3.8'

services:
  main:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 210
    environment:
      - APP_NAME=fallback
  fallback:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 80
    environment:
      - APP_NAME=fallback
  haproxy:
    image: dockercloud/haproxy
    restart: always
    depends_on:
      main:
        condition: service_healthy
      fallback:
        condition: service_healthy
    links:
      - main
      - fallback
    ports:
      - 8080:210
      - 80
